puppetlabs/gatling-puppet-load-test

- dev/beaker/01_install_required_module_and_binaries.rb
- dev/beaker/apply_manifests.rb
- dev/beaker/clone_gatling-puppet-load-test.rb
- dev/beaker/target_machine.yml
I through both tickets into one PR because they're so small, and related.
If you have a centos-6 box with puppet installed, you can test it with
```bash
beaker --log-level debug --hosts dev/beaker/target_machine.yml --tests dev/beaker/
```
You'll have to put the hostname for your centos box into `target_machine.yml` first
> Server 566 and 580 apply manifests clone repo

- proxy-recorder/launch-gatling-proxy.sh
Gatling outputs the response body text in a different folder
than the directory it outputs the .scala file
> (MAINT) Tell user where response bodies are output

- dev/beaker/20_install_required_module_and_binaries.rb
- dev/manifests/setup_jjb.pp
This commit removes the manual EPEL setup and instead just relies on the
stahnma-epel module. The result is less code, and more supported platforms.
> (MAINT) Use stahnma-epel module

- simulation-runner/config/scenarios/foss-puppetserver210-catalogzero-1.json
- simulation-runner/retrieve-agent-ssl-certs.sh
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/FOSSPuppetserver210CatalogZero.scala
This commit does the following:
* Adds an explicit path to the puppet executable for the
`retrieve-agent-ssl-certs.sh` script, so that it will work with
puppet 4.0+ out of the box.  (Backward incompatible with Puppet 3,
but we should be testing that more and more rarely in the future.)
* Fixes a few bugs/typos in the "Foss PuppetServer 2.1.0" sim
> (MAINT) Fix foss 2.1.0 sim, improve cert script

- jenkins-integration/beaker/install/foss/40_install_modules.rb
- jenkins-integration/lib/puppet/gatling/config.rb
- jenkins-integration/scripts/foss_install.sh
This commit adds simple module installation support using
librarian-puppet. Modules are specified in
jenkins-integration/config/nodes/*.json node config files, and installed
into the default production environment.
> (SERVER-712) Initial support for basic module installation

- jenkins-integration/beaker/install/foss/40_install_modules.rb
- jenkins-integration/lib/puppet/gatling/config.rb
This commit adds an additional property to the node config JSON called
'environment' which specifies which directory environment the associated
modules will be installed to.
The default 'production' environment is used if the property is empty or
missing.
> (SERVER-713) Add directory environment support

- jenkins-integration/beaker/install/foss/50_install_modules.rb
- jenkins-integration/beaker/install/foss/60_classify_nodes.rb
- jenkins-integration/config/nodes/example-node1.json
- jenkins-integration/config/nodes/example-node2.json
- jenkins-integration/config/nodes/example-node3.json
- jenkins-integration/lib/puppet/gatling/config.rb
This commit adds support for classifying agent nodes with classes
specified in the node config JSON. Each node config will be a Puppet
node definition in the appropriate environment-specific site.pp file.
---
Note this is FOSS only, as the Node Classifier will be used for the PE implementation. This is work that still needs to be done, and will probably be a subsequent PR under the same JIRA ticket number.
> (SERVER-687) Classify agent nodes

- .gitignore
- jenkins-integration/Gemfile
- jenkins-integration/beaker/install/shared/validate_classification.rb
- jenkins-integration/config/nodes/example-node1.json
- jenkins-integration/lib/puppet/gatling/config.rb
- jenkins-integration/scripts/foss_install.sh
- jenkins-integration/scripts/pe_install.sh
This commit adds a beaker script that will query the master's HTTP API
and validate that each node will receive the correct classes during the
catalog request.
This beaker script requires that each node already has an SSL
certificate and private key on the master. Unfortunately there is no
automation for putting the certificate and key on the master yet,
see SERVER-787.
This validation script will likely be executed as the very last thing
prior to launching Gatling.
> (SERVER-780) Validate node classification

- jenkins-integration/beaker/install/shared/70_install_hiera.rb
- jenkins-integration/config/hieras/basic-example/hiera.yaml
- jenkins-integration/config/hieras/basic-example/hieradata/common.json
- jenkins-integration/config/hieras/basic-example/hieradata/common.yaml
- jenkins-integration/config/nodes/example-node3.json
- jenkins-integration/config/scenarios/example-scenario.json
- jenkins-integration/lib/puppet/gatling/config.rb
- jenkins-integration/scripts/foss_install.sh
- jenkins-integration/scripts/pe_install.sh
This commit adds support for optionally specifying a Hiera "tree" as
part of the scenario. Each hiera tree is made up a hiera.yaml
configuration file and multiple data directories.
Installation will copy the hiera.yaml file to the master, and copy the
data directories into place as specified by :datadir: properties in
hiera.yaml.
> (SERVER-714) Add Hiera support

- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/PE201523CatalogZero.scala
The java.util.UUID import was not included in the initial SG recording,
which made it unusable for gatling runs. This commit adds the needed
import.
> (PE-12968) Add UUID import to SG recording

- simulation-runner/README-GENERATING-AGENT-SIMULATIONS.md
Previously the README for the agent simulations only referenced the
legacy endpoints. This commit adds the new v3 api endpoints for Puppet
4/Server 2 gatling runs.
> (PE-12968) Update agent simulations readme for v3 api endpoints

- jenkins-integration/beaker/install/shared/70_install_hiera.rb
- jenkins-integration/beaker/install/shared/r10k_deploy.rb
- jenkins-integration/config/nodes/example-r10k-node.json
- jenkins-integration/config/r10ks/basic.yaml
- jenkins-integration/config/scenarios/example-r10k-scenario.json
- jenkins-integration/lib/puppet/gatling/config.rb
- jenkins-integration/scripts/foss_install.sh
- jenkins-integration/scripts/pe_install.sh
This commit adds the beginnings of configuring the master via an r10k
control repository. It goes so far as to run "r10k deploy" to map the
repository branches to Puppet environment directories, but does not do
anything after that like wire up any hiera.yaml configuration.
> (SERVER-852) Partial r10k support

- README_CONFIG_FILE_MADNESS.md
Instead of my personal nwolfe/puppet-loadtest module that is old,
irrelevant, and replaced by puppetlabs/test-catalogs.
> (MAINT) Update example to use test-catalogs

- jenkins-integration/jenkins-jobs/common/scripts/job-steps/020_install_pe.sh
This commit adds back in some calls to some code that will set up permissive auth.conf on the server and then restart it, so that Gatling can connect without getting 403 errors.
> (SERVER-1463) fix auth so gatling can connect to server

- proxy-recorder/process_gatling_recording.rb
- simulation-runner/README-GENERATING-AGENT-SIMULATIONS.md
This PR extends the script for post-processing gatling recordings to do the following:
* Complete *all* of the processing steps listed in the docs, rather than just a subset.  Theoretically this should mean that after taking a raw recording all you need to do is run this script and then you're done.
* Finds and modifies the request body text file in addition to the scala file
* Looks for a 'node config' JSON file and generates one if one doesn't exist.
> (SERVER-1469) finish scala conversion script

- jenkins-integration/jenkins-jobs/scenarios/multi-pass-scenario/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/single-pass-scenario/Jenkinsfile
This commit adds a `server_version` section in the calls to the
pipeline() functions from the single-pass and multi-pass scenario
Jenkinsfiles.  This section is now required in that the beaker setup
step would otherwise fail if these sections are not included.
> (MAINT) Add server_version sections to single/multi pass Jenkinsfiles

- jenkins-integration/beaker/install/pe/60_classify_nodes_via_NC.rb
This commit changes the NC classification rule done for
`classify_pe_nodes` to wrap the `clientcert` in a `fact` value.
Previously, the value was not wrapped, which was erroneous and caused
nodes to not match the intended classification.
> (MAINT) Change NC classification rule to use clientcert fact

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
This commit skips over all of the logic involved in applying a custom
hiera configuration if the job definition does not include specify any
values for those settings.
> (SERVER-1452) Skip hiera configuration if no job options set

- jenkins-integration/beaker/install/shared/collect_facter_and_scenario_data.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/common/scripts/job-steps/025_collect_facter_data.sh
- jenkins-integration/lib/puppet/gatling/config.rb
This commit writes facter data and some information about the
gatling scenario to a known location, so that the
puppet-gatling-jenkins-plugin can use it when post-processing
the gatling data after a run.
> (SERVER-1468) Add facter and scenario data

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
- jenkins-integration/jenkins-jobs/scenarios/compare-3.3-to-couch/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/multi-pass-scenario/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/single-pass-scenario/Jenkinsfile
This commit moves the logic for specifying the
PUPPET_GATLING_SIMULATION_CONFIG setting from a Jenkins workflow job
parameter down into a job parameter at the level where the pipeline is
being constructed.  This was done since a multipass pipeline needs to
allow for the simulation config to be unique per "job" it runs.
> (SERVER-1471) Move scenario config out of job params

- jenkins-integration/beaker/install/shared/60_classify_nodes_via_site_pp.rb
- jenkins-integration/beaker/install/shared/80_configure_java_args.rb
- jenkins-integration/beaker/install/shared/99_restart_server.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/common/scripts/job-steps/080_configure_java_args.sh
- jenkins-integration/jenkins-jobs/scenarios/compare-3.3-to-couch/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/multi-pass-scenario/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/single-pass-scenario/Jenkinsfile
- jenkins-integration/lib/puppet/gatling/config.rb
This commit adds the ability for a pipeline job to supply a new
argument, `server_java_args`, which can be used to setup custom
JAVA_ARGS which, when set, replace the ones from the Puppet Server
sysconfig file.
> (SERVER-1466) Configure custom JAVA_ARGS for pipeline jobs

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
This commit switches us from calling the `gatlingArchive()` step
in the gatling jenkins plugin to calling the `puppetGatlingArchive()`
step in the puppet-gatling-jenkins-plugin.
> (MAINT) Switch to puppet-gatling-jenkins-plugin

- jenkins-integration/beaker/install/foss/80_run_agent_on_master.rb
- jenkins-integration/beaker/install/shared/60_classify_nodes_via_site_pp.rb
- jenkins-integration/beaker/install/shared/99_restart_server.rb
- jenkins-integration/jenkins-jobs/common/scripts/job-steps/020_install_oss.sh
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-stable/Jenkinsfile
- simulation-runner/config/scenarios/foss25x-medium-10.json
This commit adds logic to perform an agent run on a FOSS SUT before
kicking off the Gatling run.  This is needed in order to ensure that all
of the necessary directories on the master have been created before
concurrent agent runs can be performed.  Without this step, some of the
first few agent runs performed via Gatling could fail due to PUP-6651.
> (SERVER-1492) Do an agent run on FOSS SUT before Gatling run

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
This commit sets facter_structured_facts to `true` for the OSS
`server_era`.  This presumes that we'll only be installing `facter` 2.x
or later for our OSS simulations, which seems safe for now.
> (MAINT) Set facter_structured_facts to true for oss server_era

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-stable/Jenkinsfile
- simulation-runner/config/scenarios/foss25x-medium-1250.json
This commit changes the oss-puppetserver jobs to use the new
foss25x-medium-1250 scenario file - simulating 1250 agents for 4
iterations with a 30 minute sleep between runs, roughly 2 hours for the
total run.
> (MAINT) Setup oss-puppetserver jobs to use 1250 agent, 2 hr scenario

- jenkins-integration/beaker/install/shared/copy_sut_archive_files.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
Prior to this commit, we were writing the facter data and other
CSV files into a directory called 'puppet-gatling' and a subdirectory
named after the job_name in the Jenkinsfile.  We were then
creating a similar, redundant directory structure to store the 'archive'
files in.  This commit just tweaks the logic for the 'archive' files
to re-use the existing directory structure under 'puppet-gatling'
and put the files near the facter data files.
> (MAINT) Make SUT archive file path consistent

- jenkins-integration/jenkins-jobs/common/scripts/job-steps/100_run_simulation.sh
This commit echoes the Gatling simulation id and config to the shell
before kicking off the run.  This was added just for informational
purposes when looking at the output of a Jenkins job run.
> (MAINT) Echo sim id and config to the shell before running Gatling

- jenkins-integration/jenkins-jobs/scenarios/compare-3.3-to-couch/Jenkinsfile
- simulation-runner/config/scenarios/pe-couch-medium-500-2-hours.json
- simulation-runner/config/scenarios/pe33-medium-500-2-hours.json
This commit adds scenarios for 2 hours, 500 agents for PE 3.3 vs. Couch.
The agent runtimes we've seen for PE3.3 so far are so long that I wanted
to start with a low-ish number of agents.  If the run goes well we could
try one with more agents.
> (SERVER-1465) Add 2-hour scenarios for pe33 vs. couch

- jenkins-integration/jenkins-jobs/couch-static-catalogs/Jenkinsfile
- simulation-runner/config/scenarios/pe-couch-medium-1500-1-hour.json
In the previous PRs for this ticket, I added a "no static catalogs"
setup to the existing pe33-vs-couch job.  This worked fine, but
because both couch configurations perform so much better than the PE3.3
run, it was hard to visualize the perf delta between the two couch
runs (with and without static catalogs).  This commit introduces
a new job that will strictly focus on couch, with and without
static catalogs.
The first few iterations of this are just going to be used to establish
a baseline for how many agents the server can handle, given a 12G heap
size.  This is intended to be run on the dev jenkins server, not the
production one.  Once we have some data about that, I'll file
a cleanup PR that sets up the final configurations for use in production,
and will run multiple scenarios with …
> (SERVER-1559) Standalone static catalogs test

- jenkins-integration/jenkins-jobs/scenarios/couch-static-catalogs/Jenkinsfile
- simulation-runner/config/scenarios/pe-couch-medium-no-static-catalogs-250-2-hours.json
The 1250-node simulation for no-static-catalogs for couch causes
too much load for our current SUT hardware to handle.
Switching it down to 250 agents to give us samples at 250,500,1000
for no static catalogs, and hopefully make the graphs more useful.
> (SERVER-1559) Remove 1250-node sim for couch-no-static

- jenkins-integration/dev/Gemfile
Tried to spin up a dev environment today, and the `bundle install`
command failed because it pulled in beaker 3.x, which requires
Ruby 2.2.5 or something, and I am currently using Ruby 2.1.x.
Can't think of any good reason why we need that version of beaker,
nor why we shouldn't pin this dev environment to a specific version,
so this commit pins us to 2.50.0.
> (MAINT) Pin beaker to 2.50.0

- jenkins-integration/jenkins-jobs/README.md
- jenkins-integration/jenkins-jobs/README_JOBDSL_SYNTAX.md
- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week/JobDSL.groovy
The goal of this commit was to give us a mechanism for configuring the
maximum number of builds that would be retained in the history for a given
job on the Jenkins server.  The commit sets up a default value of 50
for all jobs, but also overrides this to 10 for our large 1-week job,
since history for that job will consume significantly more disk space.
It ended up that there was a solution to this particular issue that
is pretty general, and will allow users to tweak other metadata about
the jobs beyond just the build history, so that is the approach that
this commit takes.  It allows you to define a JobDSL.groovy file
alongside your Jenkinsfile, and then make calls to the JobDSL API
to modify the job.
> (SERVER-1605) Support configuration of maximum build history for job

- jenkins-integration/beaker/install/foss/30_install_dev_repos.rb
Prior to this commit, when the framework was looking for the latest
OSS Puppet Server build (from either the stable or master) branch,
it would simply look for the latest build *directory* that existed
on the builds server.  However, it is possible (and not particularly
uncommon) for a build directory to exist but not have a cent7 repo/artifact
in it (due to either the build still being in progress, or due to
cent7 not being included in the target platform list for that build).
This commit makes the script a little smarter, so that it will validate
the existence of a cent7 repo inside of the directory on the build
server before choosing that build.  If the cent7 repo doesn't exist,
the script will fall back and try the next most recent build.
> (SERVER-1603) Add check for cent7 repo, fallback when looking for build

- jenkins-integration/Gemfile
We recently upgraded to the new 3.x series of beaker, which
no longer includes PE functionality by default.  This commit
adds an explicit dependency on the beaker-pe gem to regain
that functionality.
> (MAINT) Add beaker-pe to Gemfile

- jenkins-integration/Gemfile
- jenkins-integration/beaker/install/pe/10_install_pe.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/common/scripts/job-steps/010_setup_beaker.sh
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/JobDSL.groovy
This commit adds a new job, `pe-puppetserver-latest`, which installs
the latest flanders build and runs our normal 2-hour test against it.
The JobDSL.groovy file schedules this job to run weekly on Tuesday
evenings.
> (PE-18258) Add recurring test for pe-latest

- jenkins-integration/jenkins-jobs/scenarios/compare-oss-puppetserver-stable-jit-on-off/Jenkinsfile
Adds a job which runs two oss-stable pipelines: one with jit on, and one with jit off
> (SERVER-1562) A-B test for jruby's jit mode

- jenkins-integration/jenkins-jobs/README_JOBDSL_SYNTAX.md
- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/JobDSL.groovy
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/JobDSL.groovy
- jenkins-integration/jenkins-jobs/server_config.json
This commit introduces a new config file, `server_config.json`.
In it we can list out hostnames of jenkins servers, and set
attributes for them.  The attributes will be made available to the
`JobDSL.groovy` scripts via a local variable called `serverConfig`.
This allows JobDSL configurations to do things like conditionally
modify a job based on whether it is being created in a dev environment
vs. a production environment.
> (SERVER-1662) Fix cron collisions, introduce server_config

- jenkins-integration/beaker/install/shared/60_classify_nodes_via_site_pp.rb
Fixes site.pp generation when multiple nodes are specified so that it
only emits a `default` node rule once.
> (maint) Fix site.pp generation

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/JobDSL.groovy
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/JobDSL.groovy
Previously, the oss and pe puppetserver latest jobs were configured to
run weekly on an scm poll.  This would cause Jenkins to only perform the
full Gatling job run if a commit in the gatling-puppet-load-test repo
had changed since the last job that was run.  For these jobs, we're
interested in running the jobs even if nothing in the GPLT repo has
changed - for example, if a new puppetserver nightly is available.
In this commit, the jobs have been changed to run on a cron rather than
an scm poll.  This should ensure that the jobs run every week even if
nothing in the GPLT repo itself has changed from week to week.
> (MAINT) Run puppetserver oss and pe jobs on cron instead of scm poll

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/JobDSL.groovy
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/JobDSL.groovy
This commit switches the target sut for the oss and pe-puppetserver
latest jobs from sut54 to sut56.  The hardware which corresponded to
sut54 appears to be out of commission, for now at least.  We may switch
this back later when the hardware is rehabilitated.
> (MAINT) Switch oss and pe-puppetserver jobs from sut54 to sut56

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/JobDSL.groovy
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/JobDSL.groovy
Hardware for sut54 is working again but sut56 is offline.  sut54 was
showing more consistent results from run to run than sut56 was when it
was working.  Switching back to sut54 to see if stability returns.
> (MAINT) Switch oss and pe-puppetserver jobs from sut56 to sut54

- jenkins-integration/beaker/install/foss/30_install_dev_repos.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
This PR contains two changes:
1) Enable tk-auth for latest/master OSS Puppet Server runs.
Previously, all OSS Puppet Server jobs assumed that the
use-legacy-auth-conf setting was set to 'true' and so only tried to
reconfigure the Ruby Puppet auth.conf file to enable the permissive
access needed to perform multi-node runs.  As of Puppet 5, though,
use-legacy-auth-conf will be set to 'false' by default.  This commit
updates the server config to assume that for any builds being tested
from the Puppet Server master branch, the tk-auth configuration file is
setup for permissive access.
2) Skip non-existent cent7 puppet-agent builds
Previously, the logic which tried to determine which 'latest'
puppet-agent release build to install would assume that a cent7 build
was available on the repo server …
> (SERVER-1790) Fix oss-puppetserver-latest run failures

- jenkins-integration/jenkins-jobs/README_JENKINSFILE_SYNTAX.md
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/scenarios/single-pass-scenario/Jenkinsfile
Support specifying an agent version in the Jenkinsfile data definition
alongside server_version. Fall back to 'latest' if unspecified (prior
behavior).
Signed-off-by: Moses Mendoza <moses@puppet.com>
> (SERVER-1831) enable specifying agent version

- jenkins-integration/beaker/install/foss/30_install_dev_repos.rb
- jenkins-integration/jenkins-jobs/README_JENKINSFILE_SYNTAX.md
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-stable/Jenkinsfile
This commit changes the agent_version parameter for OSS jobs to use a
distinction between 'latest' (latest successful puppet-agent build from
the master branch) vs. 'latest-release' (latest release of puppet-agent).
The oss-puppetserver-stable job now uses the 'latest-release' value for
puppet-agent whereas the other oss-puppetserver jobs continue to
implicitly use the default value of 'latest' (via not specifying a
discrete value for agent_version).
> (SERVER-1862) Introduce latest vs latest-release agent_version config

- jenkins-integration/beaker/install/foss/30_install_dev_repos.rb
A job is failing because the sha returned by get_latest_agent_version has a
single space after it.
This commit updates the get_latest_agent_version fn to strip whitespace from
the returned sha
> (MAINT) Handle whitespace in latest agent version

- jenkins-integration/beaker/install/foss/30_install_dev_repos.rb
This PR makes a few adjustments to ensure that a puppet-agent version can be found. Another PR here https://github.com/puppetlabs/puppetserver/pull/1575 should address the old SNAPSHOT version being used for builds.
> (SERVER-2034) Get perf tests working again

- jenkins-integration/beaker/install/shared/stop_sut_background_scripts.rb
Earlier today we saw a frivolous failed status for a job because this
task attempted to stop a background script, but that PID did not exist,
for reasons we couldn't determine. Since the harm in leaving that
running is minimal (nodes get wiped before reuse in most cases) but
results don't show up properly if the job is marked as a failure, we
want to ignore the case in which the PID did not exist and just
continue.
> (SERVER-2071) Don't care if background script was already stopped

- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/JobDSL.groovy
Having pe-puppetserver tests run automatically may someday be
desireable, but right now this just gets in the way by nuking SUTs that
are running tests and by causing conflicts with FOSS puppetserver. Also
this job is installing flanders. This commit disables the cron for now.
> (maint) Disable pe-puppetserver-latest cron

- Gemfile
changed gemfile to pick up a special version of beaker that has a fix to convert the AWS objects to hashs.
This will enable the host_preserved.yml to be read in, but will not enable it to use anything that leveraged
the aws instance object... like killing the instances.
This is a temp fxi until QE does the longer term fix and makes a release.
> (BKR-487) host_preserved.yml fix

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-1.7-vs-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-9k-varying-agents/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-json-vs-pson/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-max-request-per-instance/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-various-heaps/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k/Jenkinsfile
Jruby 9k does not perform adequately without jit on, so this commit
makes sure jit is always on with 9k.
> (SERVER-2071) Always have jit on for jruby9k

- jenkins-integration/jenkins-jobs/README_JENKINSFILE_SYNTAX.md
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
- jenkins-integration/jenkins-jobs/scenarios/compare-3.3-to-couch/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/couch-environment-timeout/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/couch-static-catalogs/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/multi-pass-scenario/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-various-heaps/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetdb-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/single-pass-scenario/Jenkinsfile
Previously changing gatling job parameters such as heap settings or
which garbage collector to use was impossible. This commit adds two new
parameters to all of the gatling jenkins jobs that will allow us to
override heap settings and to supply additional java args to jobs such
as garbage collector.
> (SERVER-2078) Add HEAP_OVERRIDES, JAVA_ARGS_ADDITIONS param to jobs

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/JobDSL.groovy
Right now automated runs are clobbering existing instances that may be
running tests, which is frustrating. Until we have a solid footing on
tunings to use against latest 9k, we should be disabling the job to
avoid sadness.
> (maint) Disable automatic oss-latest test runs for now

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-max-request-per-instance/Jenkinsfile
Seems like hocon expects the value to be a string and not an int. I'm
not sure if this is a limitation in hocon or in beaker's hocon helper.
> (maint) Move max requests per instance to string

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-9k/Jenkinsfile
- simulation-runner/config/scenarios/foss5x-medium-1250-12-hours.json
- simulation-runner/config/scenarios/foss5x-medium-1250-24-hours.json
Previously we only had 2 hour and 1 week runs, but having something in
the middle like 12 hr and 24 hr will be useful for chasing down some
timeouts and GC tuning. This commit adds 12 and 24 hour scenario config
files and jenkins jobs for both jruby 9k and 1.7.
> (SERVER-2089) Add scenarios and simulation configs for 12/24hr jobs

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/scenarios/latest-test-changes/Jenkinsfile
- simulation-runner/config/scenarios/foss5x-medium-1-node-1-iteration-test.json
This commit begins archiving the simulation.log.gz from each run. In
order to do this effectively we also clean up the simulation logs from
the workspace after collection.
> (SERVER-2063) Collect the simulation.log.gz from runs

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-2.x/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-1.7-vs-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-9k-varying-agents/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-max-request-per-instance/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/Jenkinsfile
We've run into a couple of cases where the heap size was not specified
and the jvm defaulted to 1/4 of system memory. To avoid that, this
commit makes explicit a default of 2gb heap for all tests that don't
specify it. HEAP_OVERRIDES will still win, so this can be altered at the
job build screen.
> (maint) Set a heap size of 2gb unless specified

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/JobDSL.groovy
Currently in order to test new combinations of node count, duration, or
catalog size a new job and scenario must be constructed. This is slow
and tedious, so this commit adds a new jenkins job that constructs a
custom gatling scenario on the fly and uses it to kick off a job against
a node config for the desired catalog size.
> (SERVER-2108) Add dynamic gatling job

- jenkins-integration/beaker/install/shared/copy_sut_archive_files.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
- jenkins-integration/jenkins-jobs/scenarios/latest-test-changes/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-2.x/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-1.7-vs-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-9k-varying-agents/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby1.7-various-heaps/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-max-request-per-instance/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-various-heaps/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/Jenkinsfile
So far it has been advantageous to collect GC logs from our gatling runs
and it has a negligible perf impact, so this commit updates all of the
jobs to archive the gc log if it exists and also adds gc logging java
args as the default java args for all jobs. Archive collection is now
configured to skip files that don't exist instead of failing.
> (SERVER-2091) Always be gc logging

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
Previously the custom scenario file was set to just the filename, and
not the full path to the scenario file, when being generated. This
unfortunately meant that none of the functions could find the file
later. This commit prepends the path to the filename to ensure it can be
found.
> (SERVER-2108) Fix scenario file path

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-2.x/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-1.7-vs-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-9k-varying-agents/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby1.7-various-heaps/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-max-request-per-instance/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-various-heaps/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetdb-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/Jenkinsfile
- simulation-runner/config/scenarios/README.md
- simulation-runner/config/scenarios/foss25x-medium-1200-2-hours.json
- simulation-runner/config/scenarios/foss25x-medium-600-2-hours.json
- simulation-runner/config/scenarios/foss25x-medium-900-2-hours.json
- simulation-runner/config/scenarios/foss5x-empty-600-2-hours.json
- simulation-runner/config/scenarios/foss5x-medium-1200-1-week.json
- simulation-runner/config/scenarios/foss5x-medium-1200-12-hours.json
- simulation-runner/config/scenarios/foss5x-medium-1200-2-hours.json
- simulation-runner/config/scenarios/foss5x-medium-1200-24-hours.json
Gatling seems to have trouble evenly distributing certain number of
agent counts, which causes gaps and hotspots. In order to avoid this,
this commit updates the scenarios to use a specific range of
num_instances (600, 900, 1200). Readme is also updated and files renamed
to reflect the changes.
> (SERVER-2110) Update num_instances to avoid gaps and hotspots

- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/Jenkinsfile
As the gc work was in flight at the same time as the configurable job,
the new job did not get the gc logging added to the Jenkinsfile. This
commit add it so the log will be collected.
> (SERVER-2091) Collect gc logs from configurable job

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/JobDSL.groovy
When running tests it is desireable to be able to choose between 9k and
1.7, so this commit adds such functionality to the puppetserver-infinite
job.
PR also includes updating the default java args to include full timestamps and tenuring details.
> (SERVER-2108) Expose jruby version to puppetserver-infinite job

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
Because the JRUBY_VERSION parameter was only added to the
puppetserver-infinite job and because we are on an older version of the
pipelines plugin, jobs that don't define the JRUBY_VERSION parameter
fail with a MissingPropertyException. In our current version of the
pipelines plugin, the recommended approach seems to be a try/catch
block. When we update to a more recent version this hackery can be
unwound.
> (SERVER-2108) Update jar customization to handle no param case

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/common/scripts/job-steps/000_provision_sut.sh
- jenkins-integration/jenkins-jobs/scenarios/spin-up-puppetserver/Jenkinsfile
- jenkins-integration/razor/ensure_razor_objects.sh
- jenkins-integration/razor/puppetserver-perf-sut-small-policy.json
- jenkins-integration/razor/puppetserver-perf-sut-small-tag.json
Create a new kind of pipeline that can be used to spin up a puppetserver
instance for some hands-on testing. This is basically a gatling run
without gatling or cleanup (so any desired artifacts will have to be
archived manually).
Mainly just want to see if this works since the dev workflow is a big hassle.
Still want to create a tool to simulate agent load without gatling, but
not sure that kicking it off immediately from this job is the right way
to go.
> (SERVER-2017) More server simulations please

- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/Jenkinsfile
Now that agent 5.4.0 and server 5.2.0 are out, this commit pins the
puppetserver-infinite job to those versions to eliminate undesired
changes in our tests.
> (SERVER-2121) Pin puppetserver-infinite job to released packages

- jenkins-integration/lib/puppet/gatling/config.rb
Until MODULES-6687 is addressed, we need to pin to an earlier version of
the inifile module, prior to refreshonly being added. This commit
updates the helper to install the 1.5.0 version of the module instead of
latest.
> (maint) Add workaround for MODULES-6687

- jenkins-integration/beaker/install/shared/clone_and_rsync.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/common/scripts/job-steps/021_clone_and_rsync.sh
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/JobDSL.groovy
In order to be able to better test how some changes to puppet affect
performance, this commit adds a job that can run gatling against a
puppet branch or ref. It clones and checks out the ref locally and
rsyncs it on top of the puppet-agent installation, which is gross, but
ultimately far simpler and faster than crafting a vanagon pipeline.
> (SERVER-2123) Create job to run gatling against puppet branch

- setup/helpers/perf_helper.rb
- spec/setup/helpers/perf_helper_spec.rb
- Updated `perf_helper.rb` to remove the `atop` and `lsof` steps
- Updated `perf_helper_spec.rb` to remove the corresponding test steps
> (maint) Updated perf_helper and spec steps

- NEW_README.md
- config/beaker_hosts/foss-perf-test.cfg
- config/beaker_hosts/pe-perf-test.cfg
- config/beaker_hosts/pe-vmpooler.cfg
- rakefile
- setup/helpers/perf_helper.rb
- setup/install_gatling/00_pre_install/05_initialize_helpers.rb
- setup/install_gatling/00_pre_install/10_etc_hosts.rb
- setup/install_gatling/00_pre_install/40_ec2_fixes.rb
- setup/install_gatling/20_foss_install/10_install_dev_repos.rb
- setup/install_gatling/40_post_install/20_use_internal_ips.rb
Updated hosts files to use ABS hypervisor
Broke out rake tasks into multiple tasks, one to provision, one to execute beaker, one to encapsulate both of those and finally, one to deprovision.
Removed workarounds for AWS that are no longer necessary: 10_etc_hosts.rb, 40_ec2_fixes.rb, 20_use_internal_ips.rb and some of the FOSS install code in perf_helper.rb
Fixed 20_foss_install/10_install_dev_repos.rb - it was missing the call to the helper method
> (QA-3457) Switch to using ABS for AWS provisioning

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
The puppetserver-infinite job uses a different base pipeline from the
other job. This commit adds the s3 upload step to it.
> (SERVER-2080) Add s3 upload step to puppetserver-infinite pipeline

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/JobDSL.groovy
(SERVER-2135)
This commit exposes a parameter on the puppetserver-infinite job to
configure the max number of active JRuby instances allowed. When set to
'default', it will use puppetserver's default of the number of CPUs - 1.
(SERVER-2103)
This commit adds a param to the puppetserver-infinite job to configure
max-requests-per-instance. It defaults to 0, meaning JRubies are never
flushed.
(SERVER-2128)
This commit adds a groovy function that walks through the params map and
exports its keys and values into a file for upload to s3.
> (SERVER-2135) (SERVER-2103) (SERVER-2128) Various gatling job additions

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
For the params map, keySet() does not return an array, but rather an
UnmodifiableSet. Therefore, `length` cannot be used to check its size;
the size() method must be used instead.
> (maint) Use size() instead of length on param map

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
Java's set type does not allow indexing with bracket notation, since it
is optimized for membership rather than for iteration. This commit
converts the params key set to an array before attempting to iterate
through it.
> (maint) Convert KeySet to Array before attempting to index

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
The s3 upload plugin requires directories to be specified with a
trailing slash, otherwise it will look for a single file with the
specified name and fail to find one. This commit adds a slash to the
folder name we want to upload.
> (maint) Add '/' to file path of s3 upload

- jenkins-integration/Gemfile
* scooter now has an upper bound at 0.12.1
* this is a vulnerability as above, but will update when scooter allows for 0.16+
> (maint) CVE-2017-17718 net-ldap CVE

- setup/helpers/perf_helper.rb
- spec/setup/helpers/perf_helper_spec.rb
The following tests have been added:
set_etc_hosts
setup_r10k
perf_install_pe
has_cent7_repo?
get_cent7_repo
get_latest_server_version
get_latest_agent_version
get_latest_release_agent_version
~~`perf_install_pe` still needs some work. I'm not sure how `@options[:answers]` should be handled and I need to circle back on some of the other TODO items. Any suggestions are appreciated.~~
EDIT: I've updated `perf_install_pe` to remove `use_meep`, updated `get_cent7_repo` to mock `has_cent7_repo`, and moved the `@options[:answers]` check. This should be ready to merge now.
> (SLV-15) Add tests to perf_helper_spec

- rakefile
Updated the `performance` task to run the `performance_provision_with_abs` unless:
1) `ABS_RESOURCE_HOSTS` has been specified
or
2) `BEAKER_HOSTS` IS NOT set to `pe-perf-test.cfg` or `foss-perf-test.cfg`
Updated the `performance_without_provision` task to only add `ABS_RESOURCE_HOSTS` if `BEAKER_HOSTS` IS set to `pe-perf-test.cfg` or `foss-perf-test.cfg`
> (maint) Fix abs provisioning issue

- config/beaker_hosts/foss-vmpooler.cfg
- rakefile
- setup/helpers/perf_helper.rb
- setup/install_gatling/40_post_install/30_final_puppet_run.rb
- setup/options/options_common.rb
- setup/options/options_foss.rb
- setup/options/options_pe.rb
This gets us closer to an easier to use setup.  It also helps because we can tell exactly which setup file is needed and in what order, for foss vs. pe.
> (slv-89) use beaker options files for various flavors of gplt setup

- NEW_README.md
- rakefile
- simulation-runner/src/main/scala/com/puppetlabs/gatling/runner/PuppetGatlingRunner.scala
- tests/gatling_kickoff.rb
If a Gatling scenario is aborted the reports may not be generated. Gatling can be run in reports only mode to create the reports for a previous run by setting the `reportsOnly` property when running via `Gatling.fromMap(props.build)`. The path of the result folder containing a valid `simulation.log` file must be specified.
`gatling_kickoff.rb` has been updated to check the value of the environment variable `PUPPET_GATLING_REPORTS_ONLY`. If it is equal to "true" that value and the value of the `PUPPET_GATLING_REPORTS_TARGET` variable are passed with the `sbt run` command on the metrics node. Otherwise these variables are passed with "false" and "".
`PuppetGatlingRunner.scala` has been updated to check `PUPPET_GATLING_REPORTS_ONLY`; if it is equal to true the `reportsOnly` property is set …
> (SLV-100) Implement reports-only run

- rakefile
After the previous fix to the BEAKER_HOSTS check in performance_provision_with_abs the acceptance task works as expected if BEAKER_HOSTS is not specified as this task provides a default. However, the performance task fails when BEAKER_HOSTS isn't specified because the default isn't set until later in performance_without_provision, so performance_provision_with_abs is never executed. 
This fix updates the performance task to only skip calling performance_provision_with_abs if BEAKER_HOSTS is specified but is not pe-perf-test.cfg or foss-perf-test.cfg. With this fix you can run the performance task without specifying BEAKER_HOSTS and the default value will be used based on the value specified for BEAKER_INSTALL_TYPE (as expected).
> (maint) updated BEAKER_HOSTS check in performance task

- NEW_README.md
- rakefile
ABS now requires a token when making a request. The most common ways to store a token locally are in an environment variable or the user's .fog file.
`retry_abs_request` has been updated to call `get_abs_token` which first checks the ABS_TOKEN environment variable, then checks the user's .fog file for the `abs_token` parameter. If not found the test will abort.
> (SLV-112) update rakefile to use abs token

- rakefile
- setup/helpers/abs_helper.rb
- spec/setup/helpers/abs_helper_spec.rb
ABS has been updated with the new endpoints /awsdirect and /awsdirectreturn to provide a direct response for AWS host requests:
https://github.com/puppetlabs/always-be-scheduling#apiv2awsdirect
This update adds an abs_helper module to extract and encapsulate the ABS-related code used by the performance rake tasks so that it can be tested via RSpec. A corresponding abs_helper_spec file has been added with examples for critical functionality.
The performance rake tasks (`performance`, `performance_provision_with_abs`, `performance_deprovision_with_abs`) have been updated to use the new endpoints via the abs_helper module. Obsolete code and dependencies have been removed.
Requests to the prod endpoint (https://cinext-abs.delivery.puppetlabs.net/api/v2/awsdirect) currently return a 504 …
> (SLV-122) Add abs_helper and spec, update rakefile to use awsdirect endpoints

- setup/helpers/perf_helper.rb
This update to perf_helper adds a rescue to the `install rvm, bundler` step to handle cases when keys.gnupg.net fails to respond. It also updates the installed ruby version to 2.4.2.
> (SLV-189) Update rvm install in perf helper to use alternate gpg command and install ruby 2.4.2

- tests/ApplesToApples.rb
This update temporarily disables the max response time assertion until SLV-208 is complete
> (SLV-189) Disable max response time assertion

- config/beaker_hosts/pe-perf-test.cfg
This changed somewhere and that template no longer exists, this is causing CI failures, changing to a template that works.
> (maint) Update aws template name

- Gemfile
- setup/helpers/perf_helper.rb
rvm interfers with puppet agent on metrics node, so stopped setting it up as we don't need it.
Updated gemfile for dependencies that support the lost cli commands in puppet 6.
like puppet cert.  had to require beaker-pe because beaker-pe-large-environments doesn't currently handle it's dependencies correctly.
> (SLV-249) Update to support puppet 6

- proxy-recorder/launch-gatling-proxy.sh
- rakefile
- setup/helpers/perf_helper.rb
- setup/install_gatling/setup_metrics_as_agent.rb
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/PerfTestLarge.scala
- tests/ApplesToApples.rb
removed MCO requests for PerfTestLarge recording.
updated puppet and ruby versions in the recording
enables a rake task to run a presuite that uses perf_helper to setup the metrics node so it can be used to record an agent run.
modified launch gatling to stop requiring it be a git repo and to remove code that was moved to the pre-suite
removed request count assertion from ApplestoApples as it is totally dependent on the recording.
> (SLV-235) redo recordings for puppet 6

- tests/ApplesToApples.rb
- tests/acceptance.rb
- tests/helpers/perf_run_helper.rb
avg_dsk_write appeared in the assertion code periodically.  But it looks like it should be avg_disk_write in all cases.
So fixed that.
> (SLV-253) Fix CI by fixing avg_dsk -> avg_disk

- NEW_README.md
- config/env/env_setup_2019.0.1
- rakefile
- simulation-runner/config/scenarios/Scale.json
- simulation-runner/config/scenarios/Scale_med.json
- simulation-runner/config/scenarios/Scale_sm.json
- tests/Scale.rb
- tests/helpers/perf_run_helper.rb
This update adds functionality to automatically increase the agent count for the scale scenario over a specified number of iterations. The 'pe-pupppetserver' service is restarted before each iteration providing a cold-start test scenario. See the [Kick off Scale performance tests](https://github.com/puppetlabs/gatling-puppet-load-test/blob/SLV-208/NEW_README.md#kick-off-scale-performance-tests) section of the [NEW_README.md](NEW_README.md) file for instructions.
> (SLV-208) GPLT - automate scaling up node count to help find scale test limit

- .gitignore
- NEW_README.md
- rakefile
- results/RESULTS.md
- results/perf/PERF_RESULTS.md
- results/scale/SCALE_RESULTS.md
- setup/install_gatling/50_tune/10_puppet_infrastructure_tune.rb
- setup/options/options_pe.rb
- simulation-runner/config/scenarios/Scale_tiny.json
- tests/helpers/perf_run_helper.rb
This update adds `setup/install_gatling/50_tune/10_puppet_infrastructure_tune.rb` to the pre-suite. This test performs the steps to run and apply `puppet infrastructure tune` on the master if the `SCALE_TUNE` environment variable is set to 'true', so it is only run during the autoscale setup or in the standalone 'autoscale_tune' rake task.
Since the autoscale runs produce a separate 'PERF' folder for each iteration the results have been moved to a `results/perf` for individual runs / iterations and `results/scale` for the collected scale run results. The scale results also provide a `results/scale/latest` link which points to the latest 'PERF_SCALE' result folder. This is used in the autoscale rake tasks to copy the latest log output to the latest scale result folder after the beaker run …
> (SLV-246) GPLT - Run 'puppet infrastructure tune' for autoscale setup, capture puppet-metrics-collector output

- Gemfile
- tests/Scale.rb
- tests/helpers/perf_run_helper.rb
This update adds a results CSV file with the following values for each scale iteration:
* agents
* ok
* ko
* combined mean
* catalog mean
* filemeta plugins mean
* filemeta pluginfacts mean
* locales mean
* node mean
* report mean
* average CPU %
* average memory
A 'beaker environment' file has also been added to capture the relevant environment values for the scale run:
* BEAKER_INSTALL_TYPE
* BEAKER_PE_DIR
* BEAKER_PE_VER
* BEAKER_TESTS
* PUPPET_GATLING_SCALE_SCENARIO
* PUPPET_GATLING_SCALE_ITERATIONS
* PUPPET_GATLING_SCALE_INCREMENT
> (SLV-206) Add results CSV and beaker environment files to scale results

- rakefile
- setup/helpers/perf_helper.rb
- setup/install/10_install/00_install_pe.rb
- spec/setup/helpers/perf_helper_spec.rb
control repo is a public github repo.  But we were accessing it using ssh, so we needed a key.  change to http and no longer need the key.
This was driven by the untimely death of the int-resources server that were using to store the key for the repo.
> (SLV-317) remove private key for control repo

- tests/helpers/perf_run_helper.rb
The previous update allowing the base number of instances to be set via the PUPPET_GATLING_SCALE_BASE_INSTANCES environment variable has a bug requiring the value to be specified. This update fixes that issue allowing the default value to be used as expected.
> (SLV-206) Fixed bug in optional base instances

- CD4PE.md
- rakefile
- setup/helpers/abs_helper.rb
The following rake tasks have been added to create the CD4PE test environment hosts via ABS:
```
rake abs_provision_environment_cd4pe          # Provision the hosts for a cd4pe test environment via ABS
rake abs_provision_host_agent                 # Provision an agent host via ABS
rake abs_provision_host_cd4pe                 # Provision a cd4pe host via ABS
rake abs_provision_host_gitlab                # Provision a gitlab host via ABS
rake abs_provision_host_worker                # Provision a worker host via ABS
```
The [CD4PE.md](CD4PE.md) file has been added to document the installation and configuration steps.
> (SLV-287) Add rake tasks and documentation to assist manual CD4PE setup

- setup/helpers/perf_helper.rb
The GPLT pre-suite currently fails at '10_install_hiera_config' after the recent control repo update to use Hiera 5. Temporarily commenting out 'update_hiera_datadir_in_local_config'; added a TODO to remove this code.
> (SLV-342) Update perf_helper to skip update_hiera_datadir_in_local_config

- config/beaker_hosts/foss-perf-test.cfg
- config/image_templates/ec2.yaml
- rakefile
- setup/helpers/abs_helper.rb
This PR updates existing ami definitions to use the newer `c5` version and deletes ami definitions for operating systems [no longer supported by Puppet Enterprise](https://puppet.com/docs/pe/2019.0/supported_operating_systems.html).
> (SLV-341) AWS AMI instance update

- docs/abs.md
This commit adds a document describing ABS as well as how to obtain an
ABS token and add it to `$HOME/.fog`.
> (SLV-111) Add document for ABS

- simulation-runner/config/scenarios/WarmUpJit.json
- tests/ApplesToApples.rb
This commit updates the `WarmUpJit.json` data to run 300 agents in a
single 10 minute iteration.
An inaccurate comment related to this data was removed from the
`ApplesToApples.rb` test.
> (SLV-319) Set warmup 300 agents - 10 min iteration

- rakefile
This commit adds a `clean` task to the rake file. It will delete
artifacts created by running other tasks.
> (SLV-358) Add clean rake task

- rakefile
This commit updates the control repo used by the rake task from the
`puppetlabs-puppetsever_perf_control` to the
`puppetlabs-pe_perf_control_repo`.
> (SLV-338) Set rake task to pe_perf_control_repo

- setup/helpers/perf_helper.rb
- setup/install_gatling/40_post_install/10_install_hiera_config.rb
- setup/options/options_foss.rb
- setup/options/options_pe.rb
This commit removes methods (and their calls) for installing a
`hiera.yaml` file on the target hosts.  Such a file should be managed by
the control repo in order to be customized on an environment specific
basis.
> (SLV-336) Remove bespoke hiera.yaml install

- .gitignore
- NEW_README.md
This commit attempts to add explicit instructions for running the rake
tasks in the repo.  It makes no prior assumptions about the users
running environment.
Common environment variables have been broken out into their own
section.  All environment variables have been marked up as source code.
A table of contents has been added to make the document more manageable.
Some section headings have been renamed in an attempt to clarify their
meaning.
> SLV-346 Improve readability of NEW_README

- Gemfile
- setup/helpers/perf_helper.rb
This commit removes the user/password credentials when creating a
`ConsoleDispatcher` object.  With the release of scooter 4.3.1, a ca
cert acquisition bug was fixed that causes the auth to fail if it is also
passed credentials.  These credentials have been removed in order for
the dispatcher will use its native cert-based auth.
> (SLV-318) Remove credentials from scooter call

- tests/helpers/perf_run_helper.rb
This commit removes the conditional for calculating the variance
of 'cpu' process values.  These values are never evaluated due to
`next` condition prior to the conditional used to evaluate them.
This commit also updates the conditional for non-cpu values to
correct the hard-coded 10% value to use the variable
`max_baseline_variance` to determine the calculation.  This variable
is set to 15% for orch_mem and otherwise set to 10%.
> (SLV-329) Fix baseline variance math

- setup/helpers/perf_helper.rb
- spec/setup/helpers/perf_helper_spec.rb
This commit sets the `puppet_enterprise::profile::puppetdb::node_ttl`
value to `0s` in order to disable node expiration in puppetdb.
> (SLV-308) Disable node expiration

- setup/helpers/perf_helper.rb
Add `fail_test` guard calls for local execs.
Update perf_helper and its spec tests to conform to rubocop linting rules.
> (SLV-390) Fail if local execs fail 

- .gitignore
- Boltdir/site-modules/gplt/tasks/create_control_repo_from_production_env.json
- Boltdir/site-modules/gplt/tasks/create_control_repo_from_production_env.sh
- docs/tasks.md
This commit adds a bolt task for creating a control repo on a
puppet master host using the current contents of the production
environment code directory as its initial commit.
The `Boltdir` directory tree scaffolding is added to allow bolt
to automatically discover the task.
Show the task:
```
$ bolt task show
...
gplt::create_control_repo_from_production_env
...
```
Run the task:
```
bolt task run \
--no-host-key-check \
--private-key ~/.ssh/id_rsa-acceptance \
--nodes ip-10-xx-xx-xx.amz-dev.puppet.net \
gplt::create_control_repo_from_production_env
```
> (SLV-361) Create ctrl repo from prod env via bolt

- Boltdir/site-modules/gplt/tasks/create_control_repo_from_production_env.json
- Boltdir/site-modules/gplt/tasks/create_control_repo_from_production_env.sh
- docs/tasks.md
updated the gplt::create_control_repo_from_production_env task to be able to accept a public github repo to be the source of the local repo it creates.  Also accepts a branch, which it will convert to the production branch in the new repo.
This allows for easy creation of a repo to use with the simulation from any branch of any public control repo.
The intent is to then point code manager at this repo as part of setup.
updated docs on the task as well
> (SLV363)Task take public github repo as source

- NEW_README.md
- config/env/env_setup_2019.1.0
- rakefile
- setup/helpers/abs_helper.rb
- simulation-runner/config/scenarios/Soak.json
- tests/Soak.rb
This update adds the following rake tasks:
```
rake soak                                     # Run Soak setup and test for gatling
rake soak_provisioned                         # Run Soak test for gatling on previously provisioned hosts
rake soak_setup                               # Run Soak setup for gatling
```
The scenario has been updated from 10 to 14 days.
To ensure AWS instances are not reaped before the test completes and post-test steps are performed the `soak` rake task sets the reap time to 20 days. `abs_helper.rb` has been updated to allow the default reap time to be overridden by specifying the value in days with the `ABS_AWS_REAP_DAYS` environment variable.
The unnecessary assertions in `Soak.rb` have been temporarily commented out.
TODO: 
* remove unnecessary assertions in …
> (SLV-415) Soak test updates: rake tasks, duration, AWS reap time

- .travis.yaml
This commit adds a `.travis.yaml` file to configure travis-ci to
execute spec tests for this repo.
> (SLV-452) Add .travis.yaml for PR spec testing

- NEW_README.md
- config/beaker_hosts/foss-perf-test.cfg
- rakefile
- setup/helpers/gatling_config_helper.rb
- setup/helpers/perf_helper.rb
- setup/install_gatling/30_classification/50_classify_nodes_via_site_pp.rb
- setup/install_gatling/40_post_install/60_restart_server.rb
- tests/helpers/perf_run_helper.rb
This PR provides updates to make gplt compatible with a foss deployment.  These changes have been successfully tested using the [pe_perf_control_repo](https://github.com/puppetlabs/puppetlabs-pe_perf_control_repo).  The [legacy control repo](https://github.com/puppetlabs/puppetlabs-puppetserver_perf_control) is not compatible because its configuration files are sequestered in a "root_files" directory, so the hiera configuration necessary to pass perf testing is not present when that repo is used.
> (SLV-433) Update for foss compatability

- rakefile
The default install type was PE, but the default options file was for foss.
> (SLV-456) Fix defaults to not conflict

- setup/install_gatling/50_tune/10_puppet_infrastructure_tune.rb
After the recent rubocop update running the scale test setup fails when attempting to apply the tune with the following error:
```
" >> /etc/puppetlabs/code-staging/environments/production/hieradata/common.yaml
ip-10-227-0-238.amz-dev.puppet.net (perf-test-mom) executed in 0.07 seconds
Committing...
ip-10-227-0-238.amz-dev.puppet.net (perf-test-mom) 15:37:02$ curl --request POST --header "Content-Type: application/json" --data '{"commit-all": true}' --cert $(p
uppet config print hostcert) --key $(puppet config print hostprivkey) --cacert $(puppet config print localcacert) https://$(hostname):8140/file-sync/v1/commit"
bash: -c: line 0: unexpected EOF while looking for matching `"'
bash: -c: line 1: syntax error: unexpected end of file
```
This is due to an erroneous '"' at the end of the …
> (maint) Removed erroneous " from tune commit

- docs/scale_run_script.md
- util/scale_run.sh
This commit adds a bash script for automating running scale testing
against the defined reference architectures defined in the PE docs
https://puppet.com/docs/pe/latest/hardware_requirements.html
This script will run a single iteration of the "10 or fewer" architecture.  It
will then run the following iterations on three different EC2 instance
definitions to test the scale of the "Up to 4,000" architecture options.
1. Cold start run provisioning the EC2 instances.
1. 4 more cold start iterations on the instance created above.
1. 5 warm start iterations on the instances created above.
The "Monolithic with compilers" architecture is not executed.
> (SLV-414) Add scale test script

- docs/abs_utils.md
- util/abs/provision_pe_xl_nodes.rb
This update to the provision_pe_xl_nodes script adds the ability to specify options via OptionParser:
```
-h, --help                       Display the help text
--noop                       Run in no-op mode
--test                       Use test data rather than provisioning hosts
--ha                         Specifies that the environment should be set up for HA
-i, --id ID                      The value for the AWS 'id' tag
-o, --output_dir DIR             The directory where the Bolt files should be written
-v, --pe_version VERSION         The PE version to install
-t, --type TYPE                  The AWS EC2 instance type to provision
-s, --size SIZE                  The AWS EC2 volume size to specify
```
Additional updates: 
- Updated `check_nodes_yaml` with more output
- Created …
> (SLV-504) Update the provision_pe_xl_nodes script to use OptionParser

- setup/install_gatling/50_tune/10_puppet_infrastructure_tune.rb
This update replaces `heiradata` with `data` in the common.yaml path (`common_yaml_path = "/etc/puppetlabs/code-staging/environments/production/data/common.yaml"`) per the following control repo update:
https://github.com/puppetlabs/puppetlabs-pe_perf_control_repo/pull/9
> (SLV-470) Update common.yaml path in 10_puppet_infrastructure_tune

- .gitignore
- Gemfile
- spec/setup/helpers/abs_helper_spec.rb
- spec/setup/helpers/perf_helper_spec.rb
- spec/spec_helper.rb
- spec/tests/helpers/perf_run_helper_spec.rb
This update adds simplecov for spec test code coverage. A `spec_helper.rb` file has been added which configures simplecov and requires the files that should be covered by the spec tests. This currently includes `setup/helpers` and `tests/helpers`. The spec test files have been updated to require `spec_helper` instead of the files under test. 
After running the spec tests via `bundle exec rake spec` the coverage report will be displayed in the results:
```
Coverage report generated for Unit Tests to /Users/test.user/gatling-puppet-load-test/coverage. 515 / 1185 LOC (43.46%) covered.
```
An HTML report is generated at `./coverage/index.html`. Based on the current code coverage the threshold has been set to 40%.
> (SLV-526) Update spec tests to use simplecov for code coverage

- docs/tune_utils.md
- util/tune/current_settings.rb
This update adds the `util/tune/current_settings.rb` script which gets the current values for the settings updated by `pe_tune`:
```
puppet_enterprise::master::puppetserver::jruby_max_active_instances
puppet_enterprise::master::puppetserver::reserved_code_cache
puppet_enterprise::profile::console::java_args
puppet_enterprise::profile::database::shared_buffers
puppet_enterprise::profile::database::autovacuum_max_workers
puppet_enterprise::profile::database::autovacuum_work_mem
puppet_enterprise::profile::database::maintenance_work_mem
puppet_enterprise::profile::database::max_connections
puppet_enterprise::profile::database::work_mem
puppet_enterprise::profile::master::java_args
puppet_enterprise::profile::orchestrator::java_args
puppet_enterprise::profile::puppetdb::java_args …
```
> (SLV-466) Add util/tune/current_settings.rb script

- .travis.yml
- rakefile
updated rakefile to have a rubocop task and to namespace the spec test task.
test:check
link:rubocop
Also added pr:check which runs both.
Then updated travis.yml to call the new PR task.
> (SLV-430) Create rake task for PR test

- spec/tests/helpers/perf_run_helper_spec.rb
- tests/helpers/perf_run_helper.rb
- util/tune/current_settings.rb
This PR includes the following updates:
* update current_settings.rb to output the correct JSON format and write the result to ~/tmp/current_tune_settings.rb on the master
* add the following new methods to `perf_run_helper.rb`:
-- `create_perf_archive_root`
-- `capture_current_tune_settings`
* update `perf_setup` to create the archive root and capture the current settings using the new methods
* add spec tests
> (SLV-467) Update perf_setup to capture current tune settings

- setup/helpers/perf_helper.rb
- setup/install_gatling/30_classification/00_configure_code_manager.rb
- setup/options/options_pe.rb
- spec/setup/helpers/perf_helper_spec.rb
This PR updates the beaker pre-suite and options files to use code manager rather than r10k when installing PE.
> (SLV-434) Use code manager for PE installs

- docs/abs_utils.md
- util/abs/provision_pe_xl_nodes.rb
This PR updates the provision_pe_xl_nodes script to make it compatible with recent updates to the reidmv-pe_xl module.
* Add --arch option to enable defining a Large or Extra Large architecture.
* Remove the "ha" parameter in the params.json
* Process the JSON node parameters based on nodes provisioned.
> (SLV-533) Update provision_pe_xl_nodes for large

- .gitignore
- rakefile
This commit adds rake tasks for utilizing the pe_xl module's pe_xl bolt
plan.  These tasks include.
* pe_xl:deploy                  - Provision pe_xl nodes and setup arch
* pe_xl:provision               - Via provision_pe_xl_nodes.rb
* pe_xl:run_plan                - Run pe_xl bolt plan
* pe_xl:rerun_plan              - Re-run pe_xl plan
* pe_xl:clean_plan_result       - Allows re-run to occur
* pe_xl:clean                   - Delete pe_xl local file artifacts
> (SLV-546) Add pe_xl rake tasks

- spec/tests/helpers/perf_run_helper_spec.rb
- tests/helpers/perf_run_helper.rb
Added code to generate a start_epoch and end_epoch file with the epoch of the, you guessed it, start and end of the test.
Added code to use the epochs in those files as arguments to the collect_metrics_files script to generate a tarball of metrics, and scp it into the results dir.
> (SLV-355) Use CMF to get tarball of metrics

- setup/helpers/perf_helper.rb
- setup/install_gatling/10_pe_install/20_autosign_hosts.rb
This commit adds pre-suites to ensure that the puppet agent is installed
on the metric node and that its certificate is autosigned by the master.
> (SLV-549) Add pre-suite install puppet on metric

- setup/options/options_pe_xl.rb
This commit adds a beaker options file to run the pre-suites necessary
for setting up performance testing on a large architecture deployment.
> (SLV-550) Add beaker opts for large architecture

- rakefile
This commit updates the `performance_without_provision` and `performance` rake tasks
to accomodate a Large Architecture.  This is accomplished with the
addition of a new ENV var `REF_ARCH`.  If this is set to `L` the
`performance`, `performance_without_provision`, and
`performance_against_already_provisioned` rake tasks will utilize the
`pe_xl:deploy` task or attempt to use the infrastructure deployed by
said task.
Example workflows:
* Performance (provision, deploy, setup performance, run tests)
```
export BEAKER_PE_VER=2019.1.1
REF_ARCH=L bundle exec rake performance
```
* Separate stages
* Setup Large Architecture with PE installed
```
export BEAKER_PE_VER=2019.1.1
bundle exec rake pe_xl:deploy
```
* Setup performance and run tests on existing Large Architecture
```
REF_ARCH=L be rake …
```
> (SLV-551) Update rake tasks to accomodate pe_xl

- tests/helpers/perf_results_helper.rb
split_atop_csv_results splits the file into 2 files.  1 for the top section and one for the bottom.
But it was sending the empty line to the first file, and then csv lint failed on that blank line.
So I added code to supress the printing of blank lines in split_atop_csv_results
> (SLV-573) supress new lines in csv file

- NEW_README.md
- docs/rake_tasks.md
This commit adds the `REF_ARCH` environment variable to the list of
variables used in the NEW_README document.
> (SLV-565) Document REF_ARCH env var

- .travis.yml
- spec/setup/helpers/abs_helper_spec.rb
- spec/tests/helpers/perf_results_helper_spec.rb
This commit changes the ruby version defined for travis-ci to use
when executing validations to 2.5.1.
> (SLV-580) Change travis ruby version to 2.5.1

- setup/helpers/perf_helper.rb
- setup/install_gatling/30_classification/60_classify_use_loadbalancer.rb
- setup/options/options_pe_xl.rb
- spec/setup/helpers/perf_helper_spec.rb
- util/abs/provision_pe_xl_nodes.rb
This PR adds a loadbalancer node in front of the compile masters when using a Large Architecture setup.  This includes:
* Create host, and roles via provision_pe_xl
* Add pre-suite to configure loadbalancer and PE infrastructure to use it
> (SLV-575) Add loadbalancer when Large arch

- setup/install_gatling/30_classification/40_classify_nodes_via_nc.rb
This commit creates a non-perf-agent-group and adds the ntp class to it
in order to ensure that ntp is installed and running on the puppet
infrastructure nodes as well as the metrics node.
> (SLV-561) Create non-perf-agent-group add ntp

- rakefile
- setup/helpers/perf_helper.rb
- tests/helpers/perf_run_helper.rb
This PR enabled gatling to target a load balancer if it is present and to set the puppetserver auth.conf files on compile masters to allow for gatling submissions to be allowed.
> (SLV-574) Enable gatling to use loadbalancer

- setup/install/00_pre_install/00_configuration_check.rb
- tests/helpers/perf_results_helper.rb
- tests/helpers/perf_run_helper.rb
- util/metrics/collect_metrics_files.rb
This update changes the name of the staging directory in the collect_metrics_files script from `puppet_metrics_collector` to `puppet-metrics-collector` for consistency. The methods that handle the metrics collector data in `perf_run_helper` and `perf_results_helper` have also been updated.
> (SLV-589) Update collect_metrics_files to use replace underscores with hyphens in staging dir

- rakefile
- spec/tests/helpers/perf_results_helper_spec.rb
- tests/helpers/perf_results_helper.rb
- tests/helpers/perf_run_helper.rb
This update adds the `validate:performance_env_vars` as a pre-requisite for the `performance` and `performance_without_provision` tasks, and the `validate:beaker_install_type` as a pre-requisite for the `performance_provision_with_abs` task.
The `validate:validate_performance_env_vars` task currently invokes the `validate:baseline_pe_version` task which verifies the `BASELINE_PE_VER` environment variable if specified. Additional validations can be added here.
The `validate:beaker_install_type` task extracts the existing verification of `BEAKER_INSTALL_TYPE` and also verifies `BEAKER_PE_VER` and `BEAKER_PE_DIR` for 'pe', `PACKAGE_BUILD_VERSION` and `PUPPET_AGENT_VERSION` for 'foss'.
To avoid duplication the code to perform the BigQuery query has been extracted to `perf_results_helper.rb`; …
> (SLV-512) Update rakefile to validate environment variables before executing performance tasks

- setup/helpers/perf_helper.rb
- setup/install_gatling/40_post_install/30_final_puppet_run.rb
- setup/install_gatling/50_tune/10_puppet_infrastructure_tune.rb
- spec/setup/helpers/perf_helper_spec.rb
This commit updates the `30_final_puppet_run` pre-suite to ensure that
the puppet agent is run repeatedly until all changes are applied and the
exit code is `0`.
> (SLV-647) Ensure all puppet changes in post inst

- spec/tests/helpers/perf_run_helper_spec.rb
- tests/helpers/perf_run_helper.rb
This commit adds a helper to copy puppet system logs from suts to the
test runner.
> (SLV-280) Copy system logs from suts

- setup/helpers/abs_helper.rb
- spec/setup/helpers/abs_helper_spec.rb
This update modifies the 'get_abs_resource_host' method to retry the request up to a max number of attempts (currently set to 3) before failing.
> (SLV-652) Update abs_helper to retry request on invalid response code

- setup/helpers/abs_helper.rb
- spec/setup/helpers/abs_helper_spec.rb
With this update all hosts provisioned via `provision_hosts_for_roles` are written to the last_abs_resource_hosts.log file. This allows the `performance_deprovision_with_abs` rake task to be used to de-provision hosts that have been provisioned via the `util/abs/provision_pe_xl_nodes.rb` script which is used to provision hosts for the Large and XL reference architectures:
* `provision_hosts_for_role` has been updated to return the host hash rather than the hostname. It converts the keys in the `abs_resource_hosts` hash to symbols and adds the role to the hash. This provides compatibility with the `util/abs/provision_pe_xl_nodes.rb` script which expects the keys to be symbols and the role to be included.
* `provision_hosts_for_roles` has been updated to call …
> (SLV-566) Update provision_hosts_for_roles to update abs resource log

- setup/install_gatling/99_final/99_final_puppet_run.rb
- setup/options/options_foss.rb
- setup/options/options_pe.rb
- setup/options/options_pe_clamps.rb
- setup/options/options_pe_xl.rb
This commit adds a pre-suite to run puppet until all changes have been
applied on all hosts.  This is intended to get the SUTs into a desired
state prior to executing tests.
This pre-suite is also added to the options files.
> (SLV-670) Add final puppet run to pre-suite

- rakefile
This commit configures the `performance_setup` rake task to preserve
hosts by default.
> (SLV-599) Preserve hosts in performance_setup

- rakefile
- spec/setup/helpers/perf_helper_spec.rb
This commit replaces deprecated rspec stubs with `allow(Obj).to
receive(:message).and_return(obj)` syntax.  The Rakefile option to
create a deprecations log has been removed.
> (SLV-588) Fix deprecated rspec stubs

- docs/results.md
This update adds the docs/results.md file which documents the Performance and Scale test result directories.
The following PR was originally created and reviewed by the SLV team:
https://github.com/puppetlabs/gatling-puppet-load-test/pull/356
That PR has been closed and this one has been created to avoid merge / rebase conflicts.
> (SLV-680) Add results.md to document perf and scale results

- spec/tests/helpers/perf_run_helper_spec.rb
- tests/helpers/perf_run_helper.rb
This commit updates the `copy_system_logs` helper to delete the system
log file tree left over by the beaker archive_file_from helper.
> (SLV-691) Delete left over puppet logdir

- config/env/env_setup_2019.2.1
This update adds the `config/env/env_setup_2019.2.1` file for Lovejoy testing.
> (SLV-661) Add env_setup_2019.2.1

- tests/helpers/perf_run_helper.rb
This update adds a step to copy_scale_results to copy the entire perf results dir to each scale iteration's results.
> (SLV-704) Update copy_scale_results to copy the perf results dir

- tests/ApplesToApples.rb
- tests/acceptance.rb
This commit adds conditional guards around the baseline_assert step
because it will fail if a baseline has not been set.
> (SLV-706) Guard baseline_assert step

- spec/tests/helpers/perf_run_helper_spec.rb
- tests/helpers/perf_run_helper.rb
This commit updates the logic for squelching failures that are positive.
These should only be throttled for memory values, in the sense that less
is better than more.  Other relationships do not require suppression at
this time.  This logic should be removed when SLV-716 is resolved.
> (SLV-708) Skip better performance for memory

- .rubocop.yml
- lib/cli.rb
- spec/tests/helpers/perf_run_helper_spec.rb
- tests/helpers/perf_run_helper.rb
This commit adds the `save_average_compile_time` helper to to the
PerfRunHelper module.  This helper queries puppetdb for the
"config_retrieval" and "total" values associated with metrics data from
the reports endpoint.  This query is constrained to a time range bound
by the start_epoch and end_epoch instance values associated with the
code at runtime.
Spec tests for this helper are added as well.
> (SLV-656) Add save_average_compile_time helper

- README.md
- simulation-runner/config/scenarios/pe-trial.json
- tests/helpers/perf_run_helper.rb
- tests/pe-trial.rb
This commit adds a pe-trial performance test and a simulation scenario
configuration of the same name.  These files facilitate the testing of a
small standard installation when provided the following command:
The PE version and directory can be customized as needed, but the other
environment variables are tailored specifically for the purposes of this
test.
```
BEAKER_TESTS=tests/pe-trial.rb \
PUPPET_GATLING_SCENARIO=pe-trial.json \
PUPPET_GATLING_SCALE_TUNE_FORCE=true \
ABS_AWS_MASTER_SIZE=m5.large \
BEAKER_PE_VER=2019.1.0 \
BEAKER_PE_DIR=http://enterprise.delivery.puppetlabs.net/archives/releases/2019.1.0 \
BEAKER_INSTALL_TYPE=pe \
bundle exec rake performance
```
> (SLV-447) Add pe-trial performance test

- tests/helpers/perf_run_helper.rb
This commit disables the call to save_average_transaction_time.  This
method appears to be causing beaker to crash due to the puppetdb data
causing beaker to run out of memory.  This commit should be reverted as
part of SLV-724.
> (SLV-719) Disable save_average_transaction_time

- tests/helpers/perf_run_helper.rb
This commit updates the override maximum for orchestrator memory and
sets it to infinity if the PE version under test is 2019.2.
> (SLV-719) Skip orch mem validation for 2019.2

- lib/beaker_dsl.rb
- lib/beakerhelper.rb
- rakefile
This commit adds logic to the `pe_xl:provision` rake task to download the
package for the given BEAKER_PE_VER.  The pe_xl plans will use a local
`tar.gz` file for the given version from the `/tmp` directory if it is
available.  This change determines whether the given version is a
release or development version, downloads the tar file, and gzips it if
necessary in order to provide it to pe_xl.
> (SLV-609) Download pe tarballs for pe_xl

- setup/helpers/perf_helper.rb
This commit replaces the `nil` value with and empty hash value for the
interpolated PUPPET_SCALE_CLASS applied to the `perf-agent-group`.
Prior to this commit the nil value unset the class assignment causing
the desired class not to be applied when installing on top of a pe_xl
deployment.
> (SLV-733) Fix perf-agent-group classes

- tests/helpers/perf_results_helper.rb
- util/report_utils/compare_results.rb
The A2A comparison in the perf report should include the min response time. This update adds the column to the CSV file extracted via `gatling2csv` and the comparison report generated via `util/report_utils/compare_results.rb`.
> (SLV-661) Update gatling2csv and compare_results to add min column

- util/scale_run.sh
This commit removes an erroneous sub-directory from the path that is
used in the warm runs to cd into.  Prior to this commit, the script
would fail to cd into the "$test" directory because the sub-directory
does not exist.
> (SLV-772) Fix scale_run warm directory

- setup/install_gatling/30_classification/60_classify_use_loadbalancer.rb
- setup/install_gatling/99_final/99_final_puppet_run.rb
This commit adds a pre-suite step after the final puppet run to ensure
that the puppet agent service is disabled on all hosts prior to any
gatling tests.
> (SLV-738) Ensure puppet agent disabled on infra

- CD4PE.md
- README.md
- config/env/env_setup_2019.0.1
- config/env/env_setup_2019.0.2
- config/env/env_setup_2019.1.0
- config/env/env_setup_2019.2.1
- jenkins-integration/beaker/install/pe/10_install_pe.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- rakefile
- util/scale_run.sh
This commit updates BEAKER_PE_DIR references to use artifactory URIs
over the legacy enterprise locations.
> (SLV-703) Use artifactory URIs for BEAKER_PE_DIR

- util/abs/provision_pe_xl_nodes.rb
- util/report_utils/build_perf_comparison.rb
- util/report_utils/build_perf_report.rb
- util/report_utils/build_scale_csv_summary.rb
- util/report_utils/build_soak_report.rb
- util/report_utils/compare_atop.rb
- util/report_utils/compare_results.rb
- util/report_utils/csv2html.rb
- util/report_utils/extract_csv.rb
- util/report_utils/split_atop_csv.rb
This commit replaces `require` statements with `require_relative` when
requiring helper paths relative to the path location of the utility
script.  This change allows the utilities to be called outside of the
directory in which they reside while still allowing the required helper
to be found.
> (maint) Use require_relative in utils for helpers

- tests/helpers/perf_run_helper.rb
This commit updates the call to `restart_puppet_server` in
`scale_setup` to iterate over all hosts with the roles of `master` and
`compile_master`.  Prior to this commit only the master was restarted
which is not sufficient in a deployment that uses compile masters in
addition to the core master server.
> (SLV-774) Restart compilers in scale_setup

- util/report_utils/build_scale_csv_summary.rb
- util/report_utils/templates/scale_csv_summary_template.html
The `util/report_utils/build_scale_csv_summary.rb` has been updated to include failing iterations with standard deviation for each column:
- replace 'average' with 'mean'
- calculate and include the standard deviation for each column
- include a table with the failing iteration
> (SLV-728) Update the scale summary script to include failing iterations with standard deviation

- spec/tests/helpers/perf_results_helper_spec.rb
- tests/helpers/perf_results_helper.rb
This commit updates the file creation logic in the
`extract_puppetserver_metrics` helper to create discrete files per
puppetserver host.
In the scenario of using load balanced compile masters for gatling node
catalog compilation the primary master puppetserver is not utilized for
catalog compilation.  This results in empty csv data.  For this reason,
the generation of the puppetserver metrics extraction files has been
updated to no longer throw an exception in the event of invalid csv
data.  A wrapper method called `valid_csv?` has been added to get a
boolean result as to the validity of a given csv file.  In the case of
an invalid file the extraction process skips over further processing of
the file and moves on to the next step/iteration of the extraction
process.
>  (SLV-610) Separate compiler csv data

- docs/slv_environment_setup.md
- spec/util/metrics/import_metrics_files_spec.rb
- util/metrics/import_metrics_files.rb
- util/p9/metrics
json2graphite changed to json2timeseriesdb and is only in puppet-metrics-collector/files now
> (SLV-792) changed influxdb import script

- Gemfile
- tests/helpers/perf_run_helper.rb
This commit updates the variances for the following performance metrics:
* process_orchestration_services_release_avg_mem
* avg_disk_write
* puppetdb_avg_mem
Prior to this commit, the PE master branch builds consistently failed
these metrics when compared to to the 2018.1.x LTS version.  These
changes update the variances to fall above the highest failure point.
Since the 2018.1.x LTS will be replaced soon, engineering effort to
invesigate these metric failures will not be applied.
Ref:
[PE-28214](https://tickets.puppetlabs.com/browse/PE-28214)
[PE-28215](https://tickets.puppetlabs.com/browse/PE-28215)
[PDB-4635](https://tickets.puppetlabs.com/browse/PDB-4635)
> (maint) Update 2018.1 a2a variances
