- jenkins-integration/beaker/install/foss/40_clone_test_catalogs.rb
- jenkins-integration/beaker/install/foss/50_install_modules.rb
- jenkins-integration/config/nodes/example-node1.json
- jenkins-integration/config/nodes/example-node2.json
- jenkins-integration/config/nodes/example-node3.json
- jenkins-integration/config/scenarios/example-scenario.json
- jenkins-integration/lib/puppet/gatling/config.rb
- jenkins-integration/scripts/foss_install.sh
This commit adds support for installing modules from the local
test-catalogs repository as well as GitHub.
> (SERVER-762) Install modules from test-catalogs

- proxy-recorder/process_gatling_recording.rb
- simulation-runner/README-GENERATING-AGENT-SIMULATIONS.md
Rewriting the request portions of the agent run into the various
mappings can be quite tedious, so this commit adds a script to automate
that step in the process.
> (maint) Add a simple script to automate part of the recording rewriting

- simulation-runner/src/main/scala/com/puppetlabs/gatling/runner/ConfigDrivenSimulation.scala
Putting this up for comment. I'm doing a long run with this code to see how successful it is, but I figured people might want to look at it in the mean time.
> [For Review Only] (SERVER-1050) Fix clumping issue

- jenkins-integration/razor/README.md
- jenkins-integration/razor/ensure_razor_objects.sh
- jenkins-integration/razor/puppetserver-perf-driver-policy.json
- jenkins-integration/razor/puppetserver-perf-driver-tag.json
- jenkins-integration/razor/puppetserver-perf-sut-broker.json
- jenkins-integration/razor/puppetserver-perf-sut-policy.json
- jenkins-integration/razor/puppetserver-perf-sut-tag.json
This commit adds some docs about our razor configuration, as well
as some automation for the parts of it that can't be managed
by Puppet in the Ops modules.
> (PE-15721) Add razor config and docs

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/common/scripts/job_steps/000_provision_sut.sh
- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
This commit adds initial support for re-provisioning SUT nodes
(on the dedicated perf testing hardware blades) via razor.
> (SERVER-328) Automate razor provisioning of SUT nodes

- jenkins-integration/dev/README.md
This commit includes some minor updates to the instructions under the
"SUT vmpooler node - disk space" section in the
"jenkins-integration/dev/README.md" doc.
> (MAINT) Made some minor updates to the vmpooler disk space docs

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-stable/Jenkinsfile
- simulation-runner/config/scenarios/foss25x-medium-10.json
This commit adds a foss25x-medium-10 scenario file and changes the
oss-puppetserver-stable and oss-puppetserver-latest pipeline jobs to use
it.
> (SERVER-1492) Add foss25x-medium-10 scenario file

- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-stable/Jenkinsfile
- simulation-runner/config/scenarios/foss25x-medium-1250-1-week.json
- simulation-runner/config/scenarios/foss25x-medium-1250-2-hours.json
This commit adds a week long version of the oss-puppetserver-latest job
and related scenario file.
> (MAINT) Setup a week long oss-ps-latest scenario

- jenkins-integration/jenkins-jobs/README_JOBDSL_SYNTAX.md
- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/JobDSL.groovy
This commit adds a `JobDSL.groovy` file for the "OSS latest" job,
and schedules that job to run automatically, once a week, on
Monday evenings.
> (SERVER-1549) Set OSS latest job to run automatically

- proxy-recorder/launch-gatling-proxy.sh
Test code snippet is attached to PERF-167
> (PERF-167) Fix error condition in launch-gatling-proxy.sh

- proxy-recorder/launch-gatling-proxy.sh
Reverts puppetlabs/gatling-puppet-load-test#122
> Revert "(PERF-167) Fix error condition in launch-gatling-proxy.sh"

- jenkins-integration/beaker/install/shared/80_configure_java_args.rb
- jenkins-integration/beaker/install/shared/81_configure_jruby_jar.rb
- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
- jenkins-integration/jenkins-jobs/common/scripts/job-steps/081_configure_jruby_jar.sh
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-1.7-vs-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-9k-varying-agents/Jenkinsfile
- jenkins-integration/lib/puppet/gatling/config.rb
- simulation-runner/config/scenarios/foss25x-medium-1000-2-hours.json
- simulation-runner/config/scenarios/foss25x-medium-500-2-hours.json
* Create job to compare oss-latest with jruby 1.7 and 9k
* Create a job for different numbers of agents to see how jruby 9k
affects performance at different loads
> (SERVER-1776) job to compare jruby 1.7 vs 9k

- config/beaker_hosts/perf-test.cfg
- rakefile
- setup/helpers/gatling_config_helper.rb
- setup/install_gatling/00_pre_install/00_etc_hosts.rb
- setup/install_gatling/00_pre_install/10_rpm_setup.rb
- setup/install_gatling/00_pre_install/20_r10k_git_setup.rb
- setup/install_gatling/00_pre_install/30_ec2_fixes.rb
- setup/install_gatling/10_install/00_install_pe.rb
- setup/install_gatling/10_install/10_r10k_deploy.rb
- setup/install_gatling/20_classification/00_classify_nodes.rb
- setup/install_gatling/20_classification/10_enable_file_sync.rb
- setup/install_gatling/20_classification/20_sync_codedir.rb
- setup/install_gatling/30_post_install/00_use_internal_ips.rb
- setup/install_gatling/30_post_install/10_final_puppet_run.rb
- setup/install_gatling/30_post_install/20_configure_gatling_auth.rb
- setup/install_gatling/30_post_install/30_configure_permissive_server_auth.rb
- setup/install_gatling/30_post_install/40_restart_server.rb
- setup/install_gatling/30_post_install/50_disable_firewall.rb
- setup/install_gatling/30_post_install/60_install_deps.rb
- setup/install_gatling/30_post_install/70_copy_sut_archive_files.rb
Added new install_gatling directory so that we can preserve the old workflows until we have completely migrated everything into the new workflow.  We still need support for Clamps and FOSS/Gatling.
> (QA-3346) Automate perf setup for PE/Gatling

- setup/install_gatling/30_post_install/99_setup_gatling_proxy.rb
* setup for gatling proxy recording as-is on the driver machine
* install deps
* clone the repo
* copy our ssldir to metrics
* copy rsa key to MOM
> (QA-3372) Automate Gatling Driver machine setup with Beaker

- setup/install_gatling/30_post_install/99_setup_gatling_proxy.rb
needed to add a dirname to a path to get it to make the dir...
> (maint) correction to copy location

- jenkins-integration/jenkins-jobs/job_bootstrap.groovy
- jenkins-integration/jenkins-jobs/scenarios/latest-test-changes/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-2.x/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x-empty/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-5.x/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-1-week-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-12hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-1.7/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-24hr-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-1.7-vs-9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby-9k-varying-agents/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby1.7-various-heaps/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-max-request-per-instance/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k-various-heaps/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest-jruby9k/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/oss-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/pe-puppetserver-latest/Jenkinsfile
- jenkins-integration/jenkins-jobs/scenarios/puppetserver-infinite/Jenkinsfile
This PR aims for better history and defaults on jobs. It updates the jobs to default to re-provisioning hosts, and also begins collecting more artifacts.
> (maint) Minor gatling jenkins job improvements

- jenkins-integration/jenkins-jobs/scenarios/short-test/Jenkinsfile
A small job that creates some files and folders and then uploads them to s3.
> Add small s3 upload job for testing

- jenkins-integration/jenkins-jobs/common/scripts/jenkins/pipeline.groovy
This commit adds a step to the end of the common pipeline that uploads
the simulation results and all the files from the SUT to our s3 bucket.
All the files are consolidated in a folder with the job name and time
stamp, to ensure unique, identifiable entries in s3.
> (SERVER-2080) Add step to base pipeline to publish to s3

- rakefile
- simulation-runner/config/scenarios/WarmUpJit.json
- simulation-runner/src/main/scala/com/puppetlabs/gatling/runner/ConfigDrivenSimulation.scala
- spec/tests/helpers/perf_run_helper_spec.rb
- tests/ApplesToApples.rb
- tests/acceptance.rb
- tests/helpers/perf_run_helper.rb
> (SLV-133) Add PUSH_TO_BIGQUERY env var to rototiller

- NEW_README.md
- simulation-runner/config/scenarios/Soak.json
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/PerfTestLarge.scala
- tests/Soak.rb
Added a test to run the Soak scenario so that next time it will be easier.
> (SLV-247) Added Soak test and scenario

- NEW_README.md
- spec/tests/helpers/perf_run_helper_spec.rb
- tests/ApplesToApples.rb
- tests/acceptance.rb
- tests/helpers/perf_run_helper.rb
Removed Baseline_Result class in favor of a simple hash
Generalized baseline comparison logic and moved it into baseline_assert method
Updated avg_dsk_write to avg_disk_write to match property name from beaker-benchmark
Added info on querying bigquery data to readme
> (SLV-190) Add baseline results and comparison per process

- tests/acceptance.rb
- tests/helpers/perf_run_helper.rb
currently not working, disabling until fixed.
> (SLV-266) turn of per process cpu check

- CD4PE.md
Updating the doc to include a step to update the environment timeout after installing Code Manager.
> (SLV-339) Update CD4PE.md with environment timeout step

- CD4PE.md
Some updates from when I followed the docs to set it up
> Maint cd4pe doc updates

- tests/helpers/perf_run_helper.rb
This commit sets the allowable variance for
`process_orchestration_services_release_avg_mem` to 15 percent.  Other
baseline process values remain at 10 percent.
> (SLV-329) Set orch memory variance to 15 percent

- docs/load_save_dbs.md
Pre work for enabling perf runs to start with a loaded db.
> (SLV-334) Document how to load and save dbs

- docs/s3.md
added doc describing how to access our s3 bucket, and some general conventions we will use to keep organized.
> (SLV-325) Document s3 bucket

- .travis.yml
Reverts puppetlabs/gatling-puppet-load-test#299
> Revert "(MAINT) Use rubygems for travis testing"

- tests/helpers/perf_run_helper.rb
The mem usage more than doubled but is execpted.
> (maint) Ignore orch mem usage for lovejoy

- .gitmodules
- .rubocop.yml
- docs/slv_environment_setup.md
- rakefile
* Add reidmv-pe_xl as a submodule
* Create and document rake task for initializing and updating submodules
> (SLV-545) Add reidmv-pe_xl submodule

- util/abs/provision_pe_xl_nodes.rb
This commit updates the `provision_pe_xl.rb` script to create a
`beaker.cfg` file for the provisioned hosts.  This file contains the
beaker roles defined for each host.  The file is then intended to be
used when running beaker against the provisioned and deployed pe_xl
architecture.
> (SLV-564) provision_pe_xl create beaker file

- NEW_README.md
The PR makes a number of updates to the NEW_README.md file with the goal of making it easier to read.
> (SLV-578) Update NEW_README

- tests/helpers/perf_run_helper.rb
expanded the expression that finds process to track to include ace server and bolt server as puma servers.
updated the code that converts the command text into a simpler string that represents the command
updated the baseline query to grab the newly added fields for ace and bolt
> (SLV-555) Add Ace and Bolt to processes tracked

- docs/load_save_dbs.md
While attempting to complete SLV-507, got new advice on how to load dbs.
The original method worked for a DB from kearney getting loaded into Kearney, but not loading into lovejoy.
> (SLV-507) update save/load db docs

- CD4PE.md
- NEW_README.md
- config/beaker_hosts/foss-perf-test.cfg
- config/beaker_hosts/foss-vmpooler.cfg
- config/beaker_hosts/opsworks-perf-test.cfg
- config/beaker_hosts/pe-vmpooler.cfg
- config/beaker_hosts/perf-test.cfg
- docs/abs_utils.md
- rakefile
- setup/helpers/abs_helper.rb
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/OpsWorksLarge.scala
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/OpsWorksLrgPGSync.scala
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/OpsWorksMedPGSync.scala
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/OpsWorksMedium.scala
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/OpsWorksSmall.scala
- simulation-runner/src/main/scala/com/puppetlabs/gatling/node_simulations/OpsWorksSmlPGSync.scala
- spec/setup/helpers/abs_helper_spec.rb
- tests/helpers/perf_run_helper.rb
- util/p9/pres
- util/p9/sres
- util/scale_run.sh
This commit updates references to 'mom' to use 'master' to reflect
current terminology.
> (SLV-503) Update mom to master

- docs/load_save_dbs.md
This commit enhances the load db doc with the following.
* Use bash loop for repetitive commands
* Add section head for updatetime.sql to make it easier to spot
* Standardize archive location/name between backup and load sections
* Standardize whitespace
> (SLV-540) Enhance load db doc

- spec/tests/helpers/perf_run_helper_spec.rb
- tests/helpers/perf_run_helper.rb
- util/tune/current_settings.rb
created hosts dir in results, and a subdir by host role.  Then in there a subdir by host ip (since there may be more then one).
In that dir placed the current_settings.json for each host
> (SLV-671) make current_settings.json per host

- util/tune/current_settings.rb
Conf files can have the same parameter defined multiple times.  If they are the last one wins.  The code change here sets us up to get the last one instead of the current one.
That change made it also a good time to remove the exclusion mechanism since it would have to have been refactored to continue to function.
Also Fixed the reporting on the max jruby instances to be NA if there was no puppetserver conf file instead of reporting the calculated default jrubies.
> (SLV-702) handle duplicate params in conf files

- simulation-runner/config/scenarios/Scale.json
- tests/helpers/perf_run_helper.rb
This update increases the number of repetitions per scale test iteration from 1 to 2.
> (SLV-717) Increate 'num_repetitions' to 2 in Scale.json scenario

- docs/load_save_dbs.md
Prior to this commit the instructions in the updatetime.sql script would cause
resource_events to be deleted when PDB applied migration number 73 which
partitions the resource_events table.
This is due to the resource_events in the SLV data dump having older timestamps
than the reports. Max date of 2018-03-30 for resource_events and 2019-05-27 for
reports in the SLV 2019-05-29 dump.
If there is enough drift between the resource_events timestamp and the
producer_timestamp in reports the partitions created for resource_events are
newer than any of the timestamps for the resource_events. This will cause all
of the resource_events to be dropped during the migration.
The updated instructions in updatetime.sql now bumps the timestamps for all
resource_events to a range that falls within the …
> (MAINT) Update docs to account for changes in PDB resource_events

- .rubocop.yml
- jenkins-integration/jenkins-jobs/common/scripts/ops-deployment/install_ops_modules_snapshot.rb
- proxy-recorder/process_gatling_recording.rb
- spec/spec_helper.rb
- spec/tests/helpers/perf_run_helper_spec.rb
- tests/helpers/perf_results_helper.rb
- util/tune/current_settings.rb
This commit makes updates the code to resolve issues described after
updating rubocop to version 0.78.0.
> (maint) Updates for rubocop 0.78.0

- tests/helpers/perf_run_helper.rb
This commit changes the maximum allowed KOs during a scale run from a
static constant to a calculated value of 1% of instances * repetitions
during a given run.
> (SLV-775) Set max KO to 1% of instances * reps
